# Generated by Django 4.2.3 on 2023-11-22 21:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0039_remove_product_discount_threshold_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etb_id", models.CharField(max_length=50, verbose_name="ID")),
                ("first_name", models.CharField(max_length=50, verbose_name="Jméno")),
                ("last_name", models.CharField(max_length=50, verbose_name="Příjmení")),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Telefonní číslo"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Komentáře")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                ("country", models.CharField(max_length=20, verbose_name="Země")),
                (
                    "shipping",
                    models.CharField(
                        choices=[("Z", "Zásilkovna")],
                        default="Zásilkovna",
                        max_length=100,
                        verbose_name="Doprava",
                    ),
                ),
                (
                    "shipping_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=Decimal("0.00"),
                        max_digits=4,
                        verbose_name="Cena dopravy (CZK)",
                    ),
                ),
                ("address", models.CharField(max_length=250, verbose_name="Adresa")),
                (
                    "vendor_id",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=250,
                        verbose_name="ID prodejce",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Sleva (CZK)",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Celková cena (CZK)",
                    ),
                ),
                (
                    "stripe_id",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Stripe ID"
                    ),
                ),
                (
                    "zasilkovna_id",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Zásilkovna ID"
                    ),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="Zaplaceno")),
                (
                    "shipped",
                    models.BooleanField(default=False, verbose_name="Vyřízeno"),
                ),
            ],
            options={
                "verbose_name": "Objednávky",
                "verbose_name_plural": "Objednávky",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cena za kus (CZK)",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Množství"),
                ),
                ("zpusob_vyroby", models.CharField(max_length=50)),
                (
                    "velikost",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Individuální velikost",
                    ),
                ),
                (
                    "kalhotky_velikost_set",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "podprsenka_velikost_set",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pas_velikost_set",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("poznamka", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created"], name="orders_orde_created_743fca_idx"
            ),
        ),
    ]
