# Generated by Django 4.2.3 on 2023-08-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=888, max_digits=4
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0.0, max_digits=4
            ),
        ),
    ]
