# Generated by Django 4.2.3 on 2024-02-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="birthday",
            field=models.DateField(
                blank=True, null=True, verbose_name="Datum narození"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="vendor_id",
            field=models.CharField(max_length=250, verbose_name="ID prodejce"),
        ),
    ]
