# Generated by Django 4.2 on 2023-05-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="zpusob_vyroby",
            field=models.CharField(
                choices=[("K", "Konfekční velikost"), ("N", "Na míru")],
                max_length=100,
                null=True,
            ),
        ),
    ]
