# Generated by Django 4.2.3 on 2024-08-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmation_sent",
            field=models.BooleanField(default=False, verbose_name="Potvrzeni zaslane"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_sent",
            field=models.BooleanField(default=False, verbose_name="Predano dopravci"),
        ),
    ]
