# Generated by Django 4.2.3 on 2023-09-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_discount_order_etb_id_order_total_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.CharField(
                choices=[("Z", "Zásilkovna")],
                default="Zásilkovna",
                max_length=100,
                verbose_name="Doprava",
            ),
        ),
    ]
