# Generated by Django 4.2.3 on 2023-08-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_total_cost_alter_order_shipping_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=200, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
    ]
