# Generated by Django 4.2.3 on 2024-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_birthday_alter_order_vendor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="newsletter_consent",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Souhlas - newsletter",
            ),
        ),
    ]
