# Generated by Django 4.2 on 2023-05-24 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_zpusob_vyroby"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="zpusob_vyroby",
        ),
    ]
