# Generated by Django 4.2.3 on 2024-09-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_confirmation_sent_order_shipped_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="confirmation_sent",
            field=models.BooleanField(
                default=False, verbose_name="Emailove potvrzení objednávky"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipped_sent",
            field=models.BooleanField(
                default=False, verbose_name="Email předáno k dopravci"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.CharField(
                choices=[
                    ("", "Vyberte si způsob dopravy"),
                    ("P", "PPL"),
                    ("D", "PPL - Doručení domů"),
                    ("Z", "Zásilkovna"),
                    ("O", "Online"),
                    ("S", "Osobní odběr"),
                ],
                default="Zásilkovna",
                max_length=100,
                verbose_name="Doprava",
            ),
        ),
    ]
