# Generated by Django 4.2.3 on 2023-08-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_discount_alter_order_total_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0.0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0.0, max_digits=10
            ),
        ),
    ]
