# Generated by Django 4.2.3 on 2023-09-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_shipping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[("CZ", "cz"), ("SK", "sk")], max_length=20, verbose_name="Země"
            ),
        ),
    ]
