# Generated by Django 4.2.3 on 2023-08-12 17:57

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_discount_alter_order_total_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=250, verbose_name="Adresa"),
        ),
        migrations.AlterField(
            model_name="order",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Komentáře"),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[("CZ", "Česko"), ("SK", "Slovensko"), ("ER", "EU")],
                max_length=20,
                verbose_name="Země",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Sleva (CZK)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.CharField(max_length=50, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Jméno"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Příjmení"),
        ),
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.CharField(max_length=20, verbose_name="Telefonní číslo"),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Zaplaceno"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.CharField(
                choices=[("Z", "Zásilkovna"), ("O", "Osobní odběr")],
                max_length=100,
                verbose_name="Doprava",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=Decimal("0.00"),
                max_digits=4,
                verbose_name="Cena dopravy (CZK)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_id",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Stripe ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Celková cena (CZK)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
        ),
        migrations.AlterField(
            model_name="order",
            name="vendor_id",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="ID prodejce"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="zasilkovna_id",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Zásilkovna ID"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="obvod_boky",
            field=models.CharField(
                blank=True, default="-", max_length=255, verbose_name="Obvod boků"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="obvod_hrudnik",
            field=models.CharField(
                blank=True, default="-", max_length=255, verbose_name="Obvod hrudníku"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="obvod_prsa",
            field=models.CharField(
                blank=True, default="-", max_length=255, verbose_name="Obvod prsou"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Cena za kus (CZK)"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Množství"),
        ),
    ]
