# Generated by Django 4.2.3 on 2023-09-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(max_length=20, verbose_name="Země"),
        ),
    ]
