# Generated by Django 4.2.3 on 2024-03-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_orderitem_surcharge_orderitem_total_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="surcharge",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Cena za kus (CZK)"
            ),
        ),
    ]
