# Generated by Django 4.2.3 on 2024-04-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_remove_orderitem_surcharge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="surcharge",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=10,
                verbose_name="Příplatek za šití na míru (CZK)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, verbose_name="Cena (CZK)"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="Cena za kus (CZK)"
            ),
        ),
    ]
