# Generated by Django 4.2.3 on 2023-08-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_order_address_alter_order_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="obvod_body",
            field=models.CharField(
                blank=True, default="-", max_length=255, verbose_name="Velikost body"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="vendor_id",
            field=models.CharField(
                blank=True, default="-", max_length=250, verbose_name="ID prodejce"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="obvod_boky",
            field=models.CharField(
                blank=True,
                default="-",
                max_length=255,
                verbose_name="Velikost kalhotek",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="obvod_hrudnik",
            field=models.CharField(
                blank=True, default="-", max_length=255, verbose_name="Velikost pasu"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="obvod_prsa",
            field=models.CharField(
                blank=True,
                default="-",
                max_length=255,
                verbose_name="Velikost podprsenky",
            ),
        ),
    ]
