# Generated by Django 4.2.3 on 2023-10-02 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_order_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="obvod_body",
            new_name="velikost",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="obvod_boky",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="obvod_hrudnik",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="obvod_prsa",
        ),
    ]
