# Generated by Django 4.2.3 on 2024-04-25 07:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_orderitem_surcharge_orderitem_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="author_comment",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="ETB poznamka k objednavce"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Celková cena (CZK)",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="poznamka",
            field=models.CharField(max_length=50),
        ),
    ]
