# Generated by Django 4.2.3 on 2023-11-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_rename_obvod_body_orderitem_velikost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="kalhotky_velikost_set",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="pas_velikost_set",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="podprsenka_velikost_set",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
