# Generated by Django 4.2.3 on 2023-08-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_order_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="etb_id",
            field=models.CharField(default=999999, max_length=50, verbose_name="ID"),
            preserve_default=False,
        ),
    ]
