# Generated by Django 4.2.3 on 2024-05-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_order_author_comment_alter_order_total_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_id",
            field=models.CharField(
                blank=True, default="-", max_length=15, verbose_name="ID certifikatu"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.CharField(
                blank=True, default="-", max_length=15, verbose_name="Slevovy kod"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="hodnota_kuponu",
            field=models.CharField(default="-", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="slevovy_kod",
            field=models.CharField(default="-", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="etb_id",
            field=models.CharField(max_length=50, verbose_name="Efir ID"),
        ),
    ]
