# Generated by Django 4.2.3 on 2023-11-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_orderitem_velikost"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="poznamka",
            field=models.TextField(blank=True),
        ),
    ]
