# Generated by Django 4.2.3 on 2024-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_order_coupon_id_order_discount_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="certificate_from",
            field=models.CharField(default="-", max_length=20, verbose_name="Od koho"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="certificate_to",
            field=models.CharField(default="-", max_length=20, verbose_name="Komu"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.CharField(
                choices=[
                    ("", "Vyberte si způsob dopravy"),
                    ("Z", "Zásilkovna"),
                    ("O", "Online"),
                ],
                default="Zásilkovna",
                max_length=100,
                verbose_name="Doprava",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="hodnota_kuponu",
            field=models.CharField(
                default="-", max_length=20, verbose_name="Hodnota kuponu"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="slevovy_kod",
            field=models.CharField(
                default="-", max_length=20, verbose_name="Slevový kód"
            ),
        ),
    ]
