# Generated by Django 4.2.3 on 2023-11-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_orderitem_poznamka"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False, verbose_name="Vyřízeno"),
        ),
    ]
