# Generated by Django 4.2.3 on 2023-08-17 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_alter_orderitem_obvod_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="obvod_body",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="obvod_boky",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="obvod_hrudnik",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="obvod_prsa",
        ),
    ]
