# Generated by Django 4.2.3 on 2024-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_alter_order_shipping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="poznamka",
            field=models.TextField(blank=True),
        ),
    ]
