# Generated by Django 4.2.3 on 2024-05-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_alter_orderitem_poznamka"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.CharField(
                choices=[
                    ("", "Vyberte si způsob dopravy"),
                    ("P", "PPL"),
                    ("Z", "Zásilkovna"),
                    ("O", "Online"),
                ],
                default="Zásilkovna",
                max_length=100,
                verbose_name="Doprava",
            ),
        ),
    ]
