# Generated by Django 4.2.3 on 2023-08-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_remove_orderitem_obvod_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="obvod_body",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="obvod_boky",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="obvod_hrudnik",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="obvod_prsa",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="zpusob_vyroby",
            field=models.CharField(default=9, max_length=50),
            preserve_default=False,
        ),
    ]
