# Generated by Django 4.2.3 on 2024-05-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_alter_order_shipping"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=250, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="order",
            name="label",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Etiketa k doprave"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="zipcode",
            field=models.CharField(blank=True, max_length=250, verbose_name="Zipcode"),
        ),
    ]
