# Generated by Django 4.2.3 on 2024-06-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_order_city_order_label_order_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="zipcode",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Zipcode"
            ),
        ),
    ]
