# Generated by Django 4.2.3 on 2024-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_alter_order_city_alter_order_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.CharField(
                choices=[
                    ("", "Vyberte si způsob dopravy"),
                    ("P", "PPL"),
                    ("D", "PPL - Doručení domů"),
                    ("Z", "Zásilkovna"),
                    ("O", "Online"),
                ],
                default="Zásilkovna",
                max_length=100,
                verbose_name="Doprava",
            ),
        ),
    ]
