# Generated by Django 4.2.3 on 2023-09-03 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0016_alter_product_product_item_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cena za kus (CZK)",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Množství"),
                ),
                ("zpusob_vyroby", models.CharField(max_length=50)),
                (
                    "obvod_hrudnik",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("obvod_prsa", models.CharField(blank=True, max_length=50, null=True)),
                ("obvod_boky", models.CharField(blank=True, max_length=50, null=True)),
                ("obvod_body", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
