# Generated by Django 4.2.3 on 2023-09-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="poznamka",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
