# Generated by Django 4.2.3 on 2023-10-15 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_cartitem_poznamka"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
