# Generated by Django 4.2.3 on 2024-08-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=20)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "nový rozměr produktu",
                "verbose_name_plural": "Inventář",
                "indexes": [
                    models.Index(
                        fields=["product", "size"],
                        name="inventory_i_product_9d287e_idx",
                    )
                ],
            },
        ),
    ]
