# Generated by Django 4.2.3 on 2023-10-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"verbose_name": "Inventář", "verbose_name_plural": "Inventář"},
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["product"], name="inventory_i_product_f4f8f8_idx"
            ),
        ),
    ]
