# Generated by Django 4.2.3 on 2023-10-01 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0022_alter_zpusobvyroby_size"),
        ("inventory", "0002_alter_inventory_options_alter_inventory_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={
                "verbose_name": "Velikost na skladě",
                "verbose_name_plural": "Inventář",
            },
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Počet"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="catalog.velikostproduktu",
                verbose_name="Velikost",
            ),
        ),
    ]
