# Generated by Django 4.2.3 on 2023-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_inventory_options_alter_inventory_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="size",
            field=models.CharField(
                blank=True, default=0, max_length=20, verbose_name="Velikost"
            ),
            preserve_default=False,
        ),
    ]
