# Generated by Django 4.2.3 on 2023-10-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_inventory_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={
                "verbose_name": "nový rozměr produktu",
                "verbose_name_plural": "Inventář",
            },
        ),
        migrations.RemoveIndex(
            model_name="inventory",
            name="inventory_i_product_f4f8f8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="size",
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["product", "size"], name="inventory_i_product_9d287e_idx"
            ),
        ),
    ]
