# Generated by Django 4.2.3 on 2023-10-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_inventory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
