# Generated by Django 4.2.3 on 2024-08-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        editable=False, max_length=50, verbose_name="Email"
                    ),
                ),
                (
                    "saved_when",
                    models.DateTimeField(auto_now_add=True, verbose_name="Přihlášeno"),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
