# Generated by Django 4.2.3 on 2023-09-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                (
                    "saved",
                    models.DateTimeField(auto_now_add=True, verbose_name="Přihlášeno"),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
