# Generated by Django 4.2.3 on 2023-09-10 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter",
            old_name="saved",
            new_name="saved_when",
        ),
    ]
