# Generated by Django 4.2.3 on 2023-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0002_rename_saved_newsletter_saved_when"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.CharField(editable=False, max_length=50, verbose_name="Email"),
        ),
    ]
