# Generated by Django 4.2.3 on 2024-06-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Váš slevový kód:", max_length=10, unique=True
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("capacity", models.IntegerField(default=1, verbose_name="Počet")),
                ("active", models.BooleanField(verbose_name="Aktivní")),
                (
                    "redeemed",
                    models.BooleanField(default=False, verbose_name="Uplatněno"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[("Procento", "Procento"), ("Částka", "Částka")],
                        max_length=255,
                        verbose_name="Typ slevy",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Zadejte hodnotu 0. anebo absolutní hodnotu částky",
                    ),
                ),
                (
                    "discount_threshold",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Minimální částka pro uplatnění slevy",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        default="N/A",
                        max_length=10,
                        verbose_name="Nakoupeno v objednavce (ID)",
                    ),
                ),
                (
                    "certificate_from",
                    models.CharField(
                        default="-", max_length=100, verbose_name="Do koho"
                    ),
                ),
                (
                    "certificate_to",
                    models.CharField(default="-", max_length=100, verbose_name="Komu"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dárkový certifikát", "Dárkový certifikát"),
                            ("Sleva na první nákup", "Sleva na první nákup"),
                            (
                                "Odměna 30 dní po 1. nákupu",
                                "Odměna 30 dní po 1. nákupu",
                            ),
                            ("Sleva po 3 měsících", "Sleva po 3 měsících"),
                            ("Přání k svátku", "Přání k svátku"),
                            ("Osobní slevový kód", "Osobní slevový kód"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sleva",
                "verbose_name_plural": "Slevy",
            },
        ),
    ]
