# Generated by Django 4.2 on 2023-06-22 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Váš slevový kód:", max_length=10, unique=True
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                (
                    "discount",
                    models.IntegerField(
                        help_text="Sleva v procentech 0 az 100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("active", models.BooleanField()),
            ],
        ),
    ]
