# Generated by Django 4.2 on 2023-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateField(),
        ),
    ]
