# Generated by Django 4.2.3 on 2024-06-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="certificate_to",
            field=models.CharField(default="-", max_length=110, verbose_name="Komu"),
        ),
    ]
