# Generated by Django 4.2.3 on 2023-09-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0002_coupon_redeemed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="redeemed",
            field=models.BooleanField(default=False),
        ),
    ]
