# Generated by Django 4.2.3 on 2024-06-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0002_alter_coupon_certificate_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Dárkový certifikát", "Dárkový certifikát"),
                    ("Sleva na první nákup", "Sleva na první nákup"),
                    ("Odměna 30 dní po 1. nákupu", "Odměna 30 dní po 1. nákupu"),
                    ("Sleva po 3 měsících", "Sleva po 3 měsících"),
                    ("Přání k svátku", "Přání k svátku"),
                    ("Osobní slevový kód", "Osobní slevový kód"),
                    ("-", "-"),
                ],
                max_length=100,
                null=True,
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="certificate_from",
            field=models.CharField(default="-", max_length=110, verbose_name="Do koho"),
        ),
    ]
