# Generated by Django 4.2.3 on 2023-09-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0003_alter_coupon_redeemed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(verbose_name="Aktivní"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="redeemed",
            field=models.BooleanField(default=False, verbose_name="Uplatněno"),
        ),
    ]
