# Generated by Django 4.2.3 on 2023-10-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0004_alter_coupon_active_alter_coupon_redeemed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
