# Generated by Django 4.2.3 on 2023-11-06 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0006_coupon_percentage_discount_alter_coupon_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="percentage_discount",
        ),
    ]
