# Generated by Django 4.2.3 on 2023-11-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0007_remove_coupon_percentage_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="discount",
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Minimální částka pro uplatnění slevy",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("Procento", "Procento"), ("Částka", "Částka")],
                max_length=255,
                verbose_name="Typ slevy",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Zadejte hodnotu 0. anebo absolutní hodnotu částky",
            ),
        ),
    ]
