# Generated by Django 4.2.3 on 2023-11-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0008_remove_coupon_discount_coupon_discount_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="capacity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
