# Generated by Django 4.2.3 on 2024-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0012_coupon_order_id_alter_coupon_discount_threshold_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "Sleva", "verbose_name_plural": "Slevy"},
        ),
        migrations.AddField(
            model_name="coupon",
            name="certificate_from",
            field=models.CharField(default="-", max_length=20, verbose_name="Do koho"),
        ),
        migrations.AddField(
            model_name="coupon",
            name="certificate_to",
            field=models.CharField(default="-", max_length=20, verbose_name="Komu"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="order_id",
            field=models.CharField(
                default="N/A", max_length=10, verbose_name="Nakoupeno v objednavce (ID)"
            ),
        ),
    ]
