# Generated by Django 4.2.3 on 2024-06-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0013_alter_coupon_options_coupon_certificate_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="certificate_from",
            field=models.CharField(default="-", max_length=100, verbose_name="Do koho"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="certificate_to",
            field=models.CharField(default="-", max_length=100, verbose_name="Komu"),
        ),
    ]
