# Generated by Django 4.2 on 2023-04-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        default="/static/assets/img/dummyimage.jpeg",
                        upload_to="catalog/%Y/%m/%d",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("description", models.TextField(blank=True)),
                ("new", models.BooleanField(default=False)),
                ("available", models.BooleanField(default=False)),
                ("discount", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("bestseller", models.BooleanField(default=False)),
                ("headliner", models.BooleanField(default=False)),
                ("product_return", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
        ),
    ]
