# Generated by Django 4.2.3 on 2024-08-28 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import efir.settings.storage_backends


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackgroundPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        upload_to="catalog/background", verbose_name="Hlavni fotka"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hlavni fotka",
                "verbose_name_plural": "Hlavni fotka",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Celé sety", "Celé sety"),
                            ("Podprsenky", "Podprsenky"),
                            ("Kalhotky", "Kalhotky"),
                            ("Podvazkové pasy", "Podvazkové pasy"),
                            ("Body", "Body"),
                            ("Doplňky", "Doplňky"),
                            ("Dárkové certifikáty", "Dárkové certifikáty"),
                        ],
                        max_length=255,
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorie",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Jméno")),
                (
                    "email",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Zpráva")),
            ],
        ),
        migrations.CreateModel(
            name="LeftPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        upload_to="catalog/background", verbose_name="Fotka vlevo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotka vlevo",
                "verbose_name_plural": "Fotka vlevo",
            },
        ),
        migrations.CreateModel(
            name="MappingSetNaMiru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                (
                    "email",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                ("number", models.CharField(max_length=255)),
                ("set_selection", models.CharField(max_length=255)),
                ("gdpr_consent", models.BooleanField()),
                ("newsletter_consent", models.BooleanField(null=True)),
                (
                    "created",
                    models.DateTimeField(
                        default="2020-01-01T00:00:00Z", verbose_name="Vytvořeno"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dotazník šití na míru",
                "verbose_name_plural": "Dotazníky šití na míru",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("short_description", models.TextField(blank=True, max_length=50)),
                ("long_description", models.TextField(blank=True)),
                (
                    "skladem_na_miru",
                    models.BooleanField(
                        default=False, verbose_name="Skladem i na míru"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="aktivní produkt"),
                ),
                ("new", models.BooleanField(default=False)),
                ("limited", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("bestseller", models.BooleanField(default=False)),
                ("headliner", models.BooleanField(default=False)),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Sleva v procentech",
                    ),
                ),
                ("poznamka", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkty",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RightdPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        upload_to="catalog/background", verbose_name="Fotka vpravo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotka vpravo",
                "verbose_name_plural": "Fotka vpravo",
            },
        ),
        migrations.CreateModel(
            name="UniqueSetCreation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                ("surname", models.CharField(max_length=255)),
                ("birthday", models.CharField(max_length=255)),
                ("hair_color", models.CharField(max_length=255)),
                ("skin_color", models.CharField(max_length=255)),
                ("color_tone", models.CharField(max_length=255)),
                ("colors_to_avoid", models.CharField(max_length=255)),
                (
                    "other_colors",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("design_preferences", models.CharField(max_length=255)),
                ("overall", models.CharField(max_length=255)),
                ("individual_cut", models.CharField(max_length=255)),
                ("knickers_cut", models.CharField(max_length=255)),
                ("bra_cut", models.CharField(max_length=255)),
                ("activities", models.CharField(max_length=255)),
                ("preferred_details", models.CharField(blank=True, max_length=255)),
                ("gdpr_consent", models.BooleanField()),
                ("newsletter_consent", models.BooleanField(null=True)),
            ],
            options={
                "verbose_name": "Dotazník",
                "verbose_name_plural": "Dotazníky Objev svůj set",
            },
        ),
        migrations.CreateModel(
            name="ZpusobVyroby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Skladem", "Skladem"),
                            ("Na Míru", "Na Míru"),
                            ("Tištěný certifikát", "Tištěný certifikát"),
                            ("Elektronický", "Elektronický"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kalhotky",
                    models.ManyToManyField(
                        blank=True, related_name="kalhotky", to="catalog.product"
                    ),
                ),
                (
                    "podprsenky",
                    models.ManyToManyField(
                        blank=True, related_name="podprsenky", to="catalog.product"
                    ),
                ),
                (
                    "podvazkove_pasy",
                    models.ManyToManyField(
                        blank=True, related_name="podvazkove_pasy", to="catalog.product"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_set",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Set",
                "verbose_name_plural": "Product Sets",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="zpusob_vyroby",
            field=models.ManyToManyField(
                default="Skladem",
                to="catalog.zpusobvyroby",
                verbose_name="Druh kolekce",
            ),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        storage=efir.settings.storage_backends.MediaStorage(),
                        upload_to="catalog/%Y/%m/%d",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotografie",
                "verbose_name_plural": "Fotografie",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[("Procento", "Procento"), ("Částka", "Částka")],
                        max_length=255,
                        verbose_name="Typ slevy",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Zadejte hodnotu 0. anebo absolutní hodnotu částky",
                    ),
                ),
                (
                    "discount_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Minimální částka pro uplatnění slevy",
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="catalog/%Y/%m/%d")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detail certifikátu",
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="catalog_cat_name_39f70b_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["id", "slug"], name="catalog_pro_id_a44864_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="catalog_pro_name_f603c0_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created"], name="catalog_pro_created_b92f5e_idx"
            ),
        ),
    ]
