# Generated by Django 4.2 on 2023-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="image1",
        ),
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                default="/static/assets/img/dummyimage.jpeg",
                upload_to="catalog/%Y/%m/%d",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                default="/static/assets/img/dummyimage.jpeg",
                upload_to="catalog/%Y/%m/%d",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image4",
            field=models.ImageField(
                default="/static/assets/img/dummyimage.jpeg",
                upload_to="catalog/%Y/%m/%d",
            ),
        ),
    ]
