# Generated by Django 4.2.3 on 2023-07-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="body",
            name="size",
            field=models.CharField(
                blank=True, help_text="Dostupné konfekční velikosti", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="obvodboky",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L")],
                help_text="Dostupné konfekční velikosti",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="obvodhrudnik",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L")],
                help_text="Dostupné konfekční velikosti",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="obvodprsa",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("70A", "70A"),
                    ("70B", "70B"),
                    ("70C", "70C"),
                    ("75A", "75A"),
                    ("75B", "75B"),
                    ("75C", "75C"),
                    ("80A", "80A"),
                    ("80B", "80B"),
                    ("80C", "80C"),
                    ("85A", "85A"),
                    ("85B", "85B"),
                    ("85C", "85C"),
                    ("90A", "90A"),
                    ("90B", "90B"),
                    ("90C", "90C"),
                    ("95A", "95A"),
                    ("95B", "95B"),
                    ("95C", "95C"),
                    ("100A", "100A"),
                    ("100B", "100B"),
                    ("100C", "100C"),
                    ("105A", "105A"),
                    ("105B", "105B"),
                    ("105C", "105C"),
                ],
                help_text="Dostupné konfekční velikosti",
                max_length=20,
            ),
        ),
    ]
