# Generated by Django 4.2 on 2023-06-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="miniature",
            field=models.FileField(
                default="/static/assets/img/dummyimage.jpeg",
                upload_to="catalog/%Y/%m/%d",
            ),
        ),
        migrations.DeleteModel(
            name="Miniature",
        ),
    ]
