# Generated by Django 4.2 on 2023-07-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="poznamka",
            field=models.TextField(blank=True),
        ),
    ]
