# Generated by Django 4.2.3 on 2023-07-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Celé sety", "Celé sety"),
                    ("Podprsenky", "Podprsenky"),
                    ("Kalhotky", "Kalhotky"),
                ],
                max_length=255,
            ),
        ),
    ]
