# Generated by Django 4.2 on 2023-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obvodhrudnik",
            name="velikost_na_miru",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="obvodprsa",
            name="velikost_na_miru",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
