# Generated by Django 4.2.3 on 2023-08-13 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_product_stock_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock_quantity",
        ),
    ]
