# Generated by Django 4.2.3 on 2023-07-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(null=True, upload_to="catalog/%Y/%m/%d"),
        ),
    ]
