# Generated by Django 4.2 on 2023-05-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_obvodhrudnik_velikost_na_miru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obvodhrudnik",
            name="velikost_na_miru",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="obvodprsa",
            name="velikost_na_miru",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
