# Generated by Django 4.2 on 2023-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_rename_image_product_image1_remove_product_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="obvod_hrudnik",
            field=models.ManyToManyField(to="catalog.obvodhrudnik"),
        ),
        migrations.AddField(
            model_name="product",
            name="obvod_prsa",
            field=models.ManyToManyField(to="catalog.obvodprsa"),
        ),
    ]
