# Generated by Django 4.2.3 on 2023-07-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image4",
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(upload_to="catalog/%Y/%m/%d"),
        ),
    ]
