# Generated by Django 4.2 on 2023-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_obvodhrudnik_velikost_na_miru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="zpusob_vyroby",
            field=models.CharField(
                choices=[("K", "Konfekční velikost"), ("N", "Na míru")],
                max_length=100,
                null=True,
            ),
        ),
    ]
