# Generated by Django 4.2.3 on 2023-07-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_photo_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="catalog.product",
            ),
        ),
    ]
