# Generated by Django 4.2.3 on 2023-07-22 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_photo_photo_alter_photo_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="catalog.product",
            ),
        ),
    ]
