# Generated by Django 4.2 on 2023-05-19 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_product_zpusob_vyroby"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="zpusob_vyroby",
        ),
    ]
