# Generated by Django 4.2.3 on 2023-08-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zpusobvyroby",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("Skladem", "Skladem"), ("Na Míru", "Na Míru")],
                default="Konfekční velikost",
                max_length=20,
            ),
        ),
    ]
