# Generated by Django 4.2.3 on 2023-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_photo_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(upload_to="catalog/%Y/%m/%d"),
        ),
    ]
