# Generated by Django 4.2.3 on 2023-08-20 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_zpusobvyroby_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Jméno")),
                (
                    "email",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Zpráva")),
            ],
        ),
    ]
