# Generated by Django 4.2.3 on 2023-08-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_remove_product_product_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_item_id",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Product_item_ID"
            ),
            preserve_default=False,
        ),
    ]
