# Generated by Django 4.2.3 on 2023-08-28 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_alter_body_size_alter_obvodboky_size_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="available",
            new_name="limited",
        ),
    ]
