# Generated by Django 4.2.3 on 2023-08-31 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_rename_available_product_limited"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cena za kus (CZK)",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Množství"),
                ),
                ("zpusob_vyroby", models.CharField(max_length=50)),
                (
                    "obvod_body",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.body"
                    ),
                ),
                (
                    "obvod_boky",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.obvodboky",
                    ),
                ),
                (
                    "obvod_hrudnik",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.obvodhrudnik",
                    ),
                ),
                (
                    "obvod_prsa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.obvodprsa",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_size_model",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "obvod_hrudnik")},
            },
        ),
    ]
