# Generated by Django 4.2.3 on 2023-09-01 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_productsize"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_item_unique_id",
            new_name="product_item_id",
        ),
    ]
