# Generated by Django 4.2.3 on 2023-09-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_rename_product_item_unique_id_product_product_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_item_id",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Product_item_ID"
            ),
        ),
    ]
