# Generated by Django 4.2.3 on 2023-09-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_remove_product_product_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="zpusob_vyroby",
            field=models.ManyToManyField(
                default="Skladem",
                to="catalog.zpusobvyroby",
                verbose_name="Druh kolekce",
            ),
        ),
        migrations.AlterField(
            model_name="zpusobvyroby",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("Skladem", "Skladem"), ("Na Míru", "Na Míru")],
                default="Skladem",
                max_length=20,
            ),
        ),
    ]
