# Generated by Django 4.2.3 on 2023-10-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_alter_product_zpusob_vyroby_alter_zpusobvyroby_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="obvod_body",
            field=models.ManyToManyField(
                blank=True, default="", to="catalog.body", verbose_name="velikost body"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="obvod_boky",
            field=models.ManyToManyField(
                blank=True,
                default="",
                to="catalog.obvodboky",
                verbose_name="velikost kalhotek",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="obvod_hrudnik",
            field=models.ManyToManyField(
                blank=True,
                default="",
                to="catalog.obvodhrudnik",
                verbose_name="velikost pasu",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="obvod_prsa",
            field=models.ManyToManyField(
                blank=True,
                default="",
                to="catalog.obvodprsa",
                verbose_name="velikost podprsenky",
            ),
        ),
    ]
