# Generated by Django 4.2.3 on 2023-10-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_rename_body_velikostproduktu_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="velikostproduktu",
            options={"verbose_name": "velikost", "verbose_name_plural": "Velikosti"},
        ),
        migrations.AddIndex(
            model_name="velikostproduktu",
            index=models.Index(fields=["size"], name="catalog_vel_size_d1b4c8_idx"),
        ),
    ]
