# Generated by Django 4.2.3 on 2023-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_alter_velikostproduktu_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zpusobvyroby",
            name="size",
            field=models.CharField(
                choices=[("Skladem", "Skladem"), ("Na Míru", "Na Míru")], max_length=20
            ),
        ),
    ]
