# Generated by Django 4.2.3 on 2023-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0022_alter_zpusobvyroby_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zpusobvyroby",
            name="size",
            field=models.CharField(default="Skladem", max_length=20),
        ),
    ]
