# Generated by Django 4.2.3 on 2023-10-02 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_inventory_size"),
        ("catalog", "0024_alter_zpusobvyroby_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="velikost",
        ),
        migrations.DeleteModel(
            name="VelikostProduktu",
        ),
    ]
