# Generated by Django 4.2.3 on 2023-10-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0025_remove_product_velikost_delete_velikostproduktu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Celé sety", "Celé sety"),
                    ("Podprsenky", "Podprsenky"),
                    ("Kalhotky", "Kalhotky"),
                    ("Podvazkové pasy", "Podvazkové pasy"),
                    ("Body", "Body"),
                    ("Doplňky", "Doplňky"),
                    ("Dárkové_certifikáty", "Dárkové certifikáty"),
                ],
                max_length=255,
            ),
        ),
    ]
