# Generated by Django 4.2.3 on 2023-10-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0028_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="zpusob_vyroby",
            field=models.ManyToManyField(
                blank=True,
                default="Skladem",
                to="catalog.zpusobvyroby",
                verbose_name="Druh kolekce",
            ),
        ),
    ]
