# Generated by Django 4.2.3 on 2023-10-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0029_alter_product_zpusob_vyroby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zpusobvyroby",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("Skladem", "Skladem"), ("Na Míru", "Na Míru"), ("-", "-")],
                max_length=20,
            ),
        ),
    ]
