# Generated by Django 4.2.3 on 2023-10-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0030_alter_zpusobvyroby_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="zpusob_vyroby",
            field=models.ManyToManyField(
                default="Skladem",
                to="catalog.zpusobvyroby",
                verbose_name="Druh kolekce",
            ),
        ),
    ]
