# Generated by Django 4.2.3 on 2023-10-17 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0031_alter_product_zpusob_vyroby"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kalhotky",
                    models.ManyToManyField(
                        blank=True, related_name="kalhotky_set", to="catalog.product"
                    ),
                ),
                (
                    "podprsenky",
                    models.ManyToManyField(
                        blank=True, related_name="podprsenky_set", to="catalog.product"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_set",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Set",
                "verbose_name_plural": "Product Sets",
            },
        ),
    ]
