# Generated by Django 4.2.3 on 2023-10-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0032_productset"),
    ]

    operations = [
        migrations.AddField(
            model_name="productset",
            name="podvazkove_pasy",
            field=models.ManyToManyField(
                blank=True, related_name="podvazkove_pasy", to="catalog.product"
            ),
        ),
        migrations.AlterField(
            model_name="productset",
            name="kalhotky",
            field=models.ManyToManyField(
                blank=True, related_name="kalhotky", to="catalog.product"
            ),
        ),
        migrations.AlterField(
            model_name="productset",
            name="podprsenky",
            field=models.ManyToManyField(
                blank=True, related_name="podprsenky", to="catalog.product"
            ),
        ),
    ]
