# Generated by Django 4.2.3 on 2023-11-06 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0033_productset_podvazkove_pasy_alter_productset_kalhotky_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("Procento", "Procento"), ("Částka", "Částka")],
                max_length=255,
                verbose_name="Typ slevy",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=11,
                max_digits=10,
                verbose_name="Minimální částka pro uplatnění slevy",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=333,
                max_digits=10,
                verbose_name="Zadejte hodnotu 0. anebo absolutní hodnotu částky",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("Procento", "Procento"), ("Částka", "Částka")],
                        max_length=255,
                        verbose_name="Typ slevy",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Zadejte hodnotu 0. anebo absolutní hodnotu částky",
                    ),
                ),
                (
                    "threshold",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        verbose_name="Minimální částka pro uplatnění slevy",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
