# Generated by Django 4.2.3 on 2023-11-06 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0034_product_discount_type_product_threshold_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Certificate",
        ),
    ]
