# Generated by Django 4.2.3 on 2023-11-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0035_delete_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=10,
                verbose_name="Minimální částka pro uplatnění slevy",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Zadejte hodnotu 0. anebo absolutní hodnotu částky",
            ),
        ),
    ]
