# Generated by Django 4.2.3 on 2023-11-06 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0037_alter_product_threshold"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="threshold",
            new_name="discount_threshold",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="value",
            new_name="discount_value",
        ),
    ]
