# Generated by Django 4.2.3 on 2023-11-06 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0038_rename_threshold_product_discount_threshold_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount_threshold",
        ),
        migrations.RemoveField(
            model_name="product",
            name="discount_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="discount_value",
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[("Procento", "Procento"), ("Částka", "Částka")],
                        max_length=255,
                        verbose_name="Typ slevy",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Zadejte hodnotu 0. anebo absolutní hodnotu částky",
                    ),
                ),
                (
                    "discount_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Minimální částka pro uplatnění slevy",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
