# Generated by Django 4.2.3 on 2023-11-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0039_remove_product_discount_threshold_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        upload_to="catalog/background", verbose_name="Hlavni fotka"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hlavni fotka",
                "verbose_name_plural": "Hlavni fotka",
            },
        ),
        migrations.CreateModel(
            name="LeftPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        upload_to="catalog/background", verbose_name="Fotka vlevo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotka vlevo",
                "verbose_name_plural": "Fotka vlevo",
            },
        ),
        migrations.CreateModel(
            name="RightdPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        upload_to="catalog/background", verbose_name="Fotka vpravo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotka vpravo",
                "verbose_name_plural": "Fotka vpravo",
            },
        ),
    ]
