# Generated by Django 4.2.3 on 2023-11-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0039_remove_product_discount_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="first",
            field=models.BooleanField(default=False),
        ),
    ]
