# Generated by Django 4.2.3 on 2023-11-11 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0040_product_first"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="first",
        ),
    ]
