# Generated by Django 4.2.3 on 2023-12-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0040_backgroundphoto_leftphoto_rightdphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True, verbose_name="aktivní produkt"),
        ),
    ]
