# Generated by Django 4.2.3 on 2024-02-05 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0041_product_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={"verbose_name": "Detail certifikátu"},
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={"verbose_name": "Fotografie", "verbose_name_plural": "Fotografie"},
        ),
        migrations.AlterField(
            model_name="certificate",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=2,
                null=True,
                verbose_name="Sleva v procentech",
            ),
        ),
        migrations.AlterField(
            model_name="zpusobvyroby",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Skladem", "Skladem"),
                    ("Na Míru", "Na Míru"),
                    ("Tištěný", "Tištěný"),
                    ("-", "-"),
                ],
                max_length=20,
            ),
        ),
    ]
