# Generated by Django 4.2.3 on 2024-02-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0042_alter_certificate_options_alter_photo_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueSetCreation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("birthday", models.CharField(max_length=255)),
                ("hair_color", models.CharField(max_length=255)),
                ("skin_color", models.CharField(max_length=255)),
                ("color_tone", models.CharField(max_length=255)),
                ("colors_to_avoid", models.CharField(max_length=255)),
                ("design_preferences", models.CharField(max_length=255)),
                ("overall", models.CharField(max_length=255)),
                ("individual_cut", models.CharField(max_length=255)),
                ("knickers_cut", models.CharField(max_length=255)),
                ("bra_cut", models.CharField(max_length=255)),
                ("activities", models.CharField(max_length=255)),
                ("preferred_details", models.CharField(blank=True, max_length=255)),
                ("gdpr_consent", models.BooleanField()),
            ],
            options={
                "verbose_name": "Dotazník",
                "verbose_name_plural": "Dotazníky Objev svůj set",
            },
        ),
    ]
