# Generated by Django 4.2.3 on 2024-02-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0043_uniquesetcreation"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniquesetcreation",
            name="newsletter_consent",
            field=models.BooleanField(null=True),
        ),
    ]
