# Generated by Django 4.2.3 on 2024-02-29 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0045_contactmodel_delete_contactform"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingSetNaMiru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                (
                    "email",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                ("number", models.CharField(max_length=255)),
                ("set_selection", models.CharField(max_length=255)),
                ("gdpr_consent", models.BooleanField()),
                ("newsletter_consent", models.BooleanField(null=True)),
            ],
            options={
                "verbose_name": "Dotazník šití na míru",
                "verbose_name_plural": "Dotazníky šití na míru",
            },
        ),
        migrations.AddField(
            model_name="uniquesetcreation",
            name="email",
            field=models.CharField(
                max_length=50,
                null=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email",
            ),
        ),
        migrations.AddField(
            model_name="uniquesetcreation",
            name="other_colors",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
