# Generated by Django 4.2.3 on 2024-03-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0046_mappingsetnamiru_uniquesetcreation_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="skladem_na_miru",
            field=models.BooleanField(default=False, verbose_name="Skladem i na míru"),
        ),
    ]
