# Generated by Django 4.2.3 on 2024-05-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0047_product_skladem_na_miru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zpusobvyroby",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Skladem", "Skladem"),
                    ("Na Míru", "Na Míru"),
                    ("Tištěný certifikát", "Tištěný certifikát"),
                    ("Elektronický", "Elektronický"),
                ],
                max_length=20,
            ),
        ),
    ]
