# Generated by Django 4.2.3 on 2024-05-09 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0048_alter_zpusobvyroby_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappingsetnamiru",
            name="created",
            field=models.DateTimeField(
                default="2020-01-01T00:00:00Z", verbose_name="Vytvořeno"
            ),
        ),
        migrations.AlterField(
            model_name="uniquesetcreation",
            name="email",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email",
            ),
        ),
    ]
