# Generated by Django 4.2.3 on 2024-05-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0049_mappingsetnamiru_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="photo",
            field=models.ImageField(blank=True, upload_to="catalog/%Y/%m/%d"),
        ),
    ]
