# Generated by Django 4.2.3 on 2024-07-07 06:39

from django.db import migrations, models
import efir.settings.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0050_certificate_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                storage=efir.settings.storage_backends.MediaStorage(),
                upload_to="catalog/%Y/%m/%d",
            ),
        ),
    ]
